# Generated by Django 4.2 on 2024-05-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_direccion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='region',
            field=models.CharField(max_length=20),
        ),
    ]
